package coza.opencollab.unipoole.shared;

import java.util.Date;
import java.util.List;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * This is a melete module/section.
 * 
 * @author OpenCollab
 */
public class MeletePart {

    /**
     * int id generated by Melete e.g 78447013
     */
    private String id;
    /**
     * Section title e.g. "0.1 Welcome to the module"
     */
    private String title;
    /**
     * The id of the Melete module or section for which this section is a child of.
     */
    @JsonProperty("parent_id")
    private String parentId;
    private Date open;
    private Date due;
    private Date allowUntil;
    @JsonProperty("last_visit")
    private String lastVisit;
    private String status;
    /**
     * Description of the module e.g. "Start here &amp; then click on Next to
     * open up the sections."
     */
    private String description;
    private String content;
    /**
     * What type of section content is this? e.g. typeEditor
     */
    private String contentType;
    /**
     * Counter of how many times has this section been modified ?
     */
    private String version;
    /**
     * Keywords attributed to the module
     */
    private String keywords;
    /**
     * Instr , we belive this this is for any additional instructions
     */
    private String instructor;
    /**
     * Module creators userId
     */
    private String userId;
    /**
     * Module modifier userId
     */
    private String modifyUserId;
    /**
     * The date the module was created. e.g. "2013-01-29 17:01:23.0"
     */
    private Date creationDate;
    /**
     * Date when/if the module was modified.
     */
    private Date modificationDate;
    /**
     * Whats Next
     */
    private String whatsNext;
    /**
     * Sakai Content Resource for the section. Contains a byte[] for the content
     * which is usually the HMTL
     */
    @JsonIgnore
    private Resource resource;
    /**
     * For melete parts of type typeUpload
     * we include the resource
     */
    private Resource upload;
    
    /**
     * This list is set on modules to indicate the seq of the sections within 
     * that module. This list contains the section id's
     */
    private List<String> seqList;
    
    /**
     * This id specifies the order and hierarchy in which the data will be 
     * displayed in a tree structure
     */
    @JsonProperty("tt_id")
    private String sortedId;
    
    /**
     * Specifies the sortedId of the parent
     */
    @JsonProperty("tt_parent_id")
    private String sortedParentId;

    /**
     * Used to keep track of the child section sequence
     */
    @JsonIgnore
    private int nextChildId = 0;
    
    /**
     * ============== Getters and Setters ============
     */
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getParentId() {
        return parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    public Date getOpen() {
        return open;
    }

    public void setOpen(Date open) {
        this.open = open;
    }

    public Date getDue() {
        return due;
    }

    public void setDue(Date due) {
        this.due = due;
    }

    public Date getAllowUntil() {
        return allowUntil;
    }

    public void setAllowUntil(Date allowUntil) {
        this.allowUntil = allowUntil;
    }

    public String getLastVisit() {
        return lastVisit;
    }

    public void setLastVisit(String lastVisit) {
        this.lastVisit = lastVisit;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getKeywords() {
        return keywords;
    }

    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    public String getInstructor() {
        return instructor;
    }

    public void setInstructor(String instructor) {
        this.instructor = instructor;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getModifyUserId() {
        return modifyUserId;
    }

    public void setModifyUserId(String modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    public Date getModificationDate() {
        return modificationDate;
    }

    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }

    public Resource getResource() {
        return resource;
    }

    public void setResource(Resource resource) {
        this.resource = resource;
    }

    public Resource getUpload() {
        return upload;
    }

    public void setUpload(Resource upload) {
        this.upload = upload;
    }

    public String getWhatsNext() {
        return whatsNext;
    }

    public void setWhatsNext(String whatsNext) {
        this.whatsNext = whatsNext;
    }

    @Override
    public String toString() {
        return "MeleteSection{ id=" + id + ", title=" + title + ", contentType=" + contentType + ", version=" + version + ", instructor=" + instructor + ", parentId=" + parentId + ", resource=" + resource + '}';
    }

    /**
     * @return the seqList
     */
    public List getSeqList() {
        return seqList;
    }

    /**
     * @param seqList the seqList to set
     */
    public void setSeqList(List seqList) {
        this.seqList = seqList;
    }

    /**
     * @return the sortedId
     */
    public String getSortedId() {
        return sortedId;
    }

    /**
     * @param sortedId the sortedId to set
     */
    public void setSortedId(String sortedId) {
        this.sortedId = sortedId;
    }

    /**
     * @return the sortedParentId
     */
    public String getSortedParentId() {
        return sortedParentId;
    }

    /**
     * @param sortedParentId the sortedParentId to set
     */
    public void setSortedParentId(String sortedParentId) {
        this.sortedParentId = sortedParentId;
    }

    /**
     * @return the nextChildId
     */
    public int getNextChildId() {
        return ++nextChildId;
    }

    /**
     * @param nextChildId the nextChildId to set
     */
    public void setNextChildId(int nextChildId) {
        this.nextChildId = nextChildId;
    }
}
